version: "3.9"
services:
  web:
    build: .
    expose:
      - "8080"
  db:
    image: "postgres:12.9"
    environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
    expose:
      - "5432"
    volumes:
        - ./postgres-data:/var/lib/postgresql/data
