version: "3.9"
services:
  web:
    depends_on:
      - db
    image: ghcr.io/gustavgust/trellorails:main
    ports:
      - "3000:3000"
  db:
    image: "postgres:12.9"
    environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
    expose:
      - "5432"
    volumes:
        - ./postgres-data:/var/lib/postgresql/data
