version: "3.4"

services:
  db:
    image: postgres:11-alpine
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  app:
    depends_on:
      - db
    image: ghcr.io/gustavgust/trellorails:main
    links:
      - db
    volumes:
      - ruby-bundle:/usr/local/bundle
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    command: bin/docker-entrypoint

volumes:
  ruby-bundle:
  db-data:
