version: "3.9"
services:
  web:
    depends_on:
      - db
    image: ghcr.io/gustavgust/trellorails:main
    command: sh -c "bundle exec rails db:prepare && bundle exec rails server -b 0.0.0.0"
    ports:
      - "3000:3000"
  db:
    image: "postgres:12.9"
    environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
    expose:
      - "5432"
    volumes:
        - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
