server:
  http_listen_port: 0
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

client:
  url: https://181578:eyJrIjoiNTk0YzNkYTc4YmFhMzk2ZWQyYjFiMmIwZDEzYTAwODU5NjBiMzJjMiIsIm4iOiJ0cmVsbG8tcmFpbHMiLCJpZCI6NjE3NTk5fQ==@logs-prod3.grafana.net/api/prom/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*.log
