name: Server Up

on:
  workflow_run:
    workflows: [ Docker ]
    types: [ completed ]
    branches: [ main ]

jobs:
  server-up:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Docker Compose Up
        run: sudo docker-compose up -d --remove-orphans
